repos:
- repo: https://github.com/asottile/pyupgrade
  rev: v3.10.1
  hooks:
  - id: pyupgrade
    args: [--py38-plus]
- repo: https://github.com/asottile/reorder_python_imports
  rev: v3.10.0
  hooks:
  - id: reorder-python-imports
    args: [--py38-plus]
- repo: https://github.com/psf/black
  rev: "23.7.0"
  hooks:
  - id: black
    args: [--safe, --quiet]
    language_version: python3
- repo: https://github.com/pycqa/flake8
  rev: "6.1.0"
  hooks:
  - id: flake8
    language_version: python3
